### ISSUE TITLE
[Feature request] Option to ignore dots in key names and to score all keys, without specifying a list

### ISSUE THREAD

**Issue by joepio** [fwextensions/quick-score#11]
First off: thanks for creating and sharing this wonderful library!

I'm having a bit of trouble searching through my objects. My objects use http URLs as keys, and I want to search through them. Since I'm searching in Objects, I have to pass an array of keys to my QuickScore options:`new QuickScore(resourceObjArray, qsOpts)`.

However, if I pass an array of URLs, it will parse the dots inside them as paths for new keys. E.g. this key:

`https://atomicdata.dev/properties/shortname`

becomes:

`https://atomicdata` `dev/properties/shortname`

I'm not entirely sure if this is the reason why I can't search in my URL properties, but it seemed logical.

One possible solution is to change the `keys` opts to not use the dot syntax to denote subkeys, but use arrays. A bit more convenient for most, but it would mean the library becomes usable for libraries that use dots in keys.

**Comment by joepio** [comment]
Another (possibly way simpler, but still works for me) approach is to have an option to _index all keys_, and score them equally. I think this would be a really sensible default, if the value is an array of objects and the opts.key is undefined.

**Comment by joepio** [comment]
I've opted for a different (maybe very hacky) solution that doesn't require changes to QuickScore - simply serialize the entire JS object to a string, and use that! Not pretty, but fits my usecase.

**Comment by fwextensions** [comment]
Interesting.  Yes, object keys containing dots are always parsed into a path, which is why your search isn't working. 

All of the scoring libraries I've seen that work with objects assume all the objects in an array to be scored have identical, or at least very similar, shapes.  And there's usually some precedence to the keys, so a match on `title` sorts before a match on `lastName`, which is before `firstName`.  

Typically in a search UI, you might render each item's keys, like `title`, `lastName`, etc., and then highlight the key with the highest score in some distinct way, such as bold text, so the user knows what's getting matched.  I'm not sure how you'd handle that with each item having potentially multiple unique keys. 

> Another (possibly way simpler, but works even better for me) approach is to have an option to index all keys, and score them equally. I think this would be a really sensible default, if the value is an array of objects and the opts.key is undefined.

That would probably be a fairly simple change, though it would require getting each object's keys for each search.

> I've opted for a different (maybe very hacky) solution that doesn't require changes to QuickScore - simply serialize the entire JS object to a string, and use that! Not pretty, but fits my usecase.

For the values that are keyed by URLs, are you trying to search on just the values, or on the URL strings as well?  If the latter, than something like `{ data: { url: "https://...", value: "foo" } }` would make more sense, with a `["data.url", "data.value"]` `keys` array.  

I took a quick peek at your repo linked above, and the demo.  I'm guessing these [`Resource`](https://github.com/joepio/atomic-data-browser/blob/main/src/atomic-lib/resource.tsx) objects are what you're searching on?  If what you're trying to match on are the routes available on a `Resource`, I guess I'd break things down into `ResourceRoute` objects, each with a `url`, `domain`, etc. keys.  That way, all the items would have the same shape, and if you searched for `root`, you might get several results, each with a distinct `domain`.  Again, just took a quick look, so I could be off.

**Comment by joepio** [comment]
Thanks for taking the time to answer my question and dive into my own demo.

> Typically in a search UI, you might render each item's keys, like `title`, `lastName`, etc., and then highlight the key with the highest score in some distinct way, such as bold text, so the user knows what's getting matched. I'm not sure how you'd handle that with each item having potentially multiple unique keys.

Yeah, getting the highlights to work was something that I'm definitely struggling with, so I decided to move on and just not use the highlights. Although they would make the UX better, they are not essential.

> For the values that are keyed by URLs, are you trying to search on just the values, or on the URL strings as well? If the latter, than something like { data: { url: "https://...", value: "foo" } } would make more sense, with a ["data.url", "data.value"] keys array.

Hmm, yeah searching through the keys is a nasty side effect of my current 'just serialize the entire json objet lol' approach. I just changed that by turning all values into one array, thus ignoring the keys. It kind of works, and I don't _really_ need the keys ATM. Of course, getting an object with the correct keys and only searching through the values (my first suggestion) would be a bit preferable, as that would probably allow me to get the highlights working.

> I took a quick peek at your repo linked above, and the demo. I'm guessing these Resource objects are what you're searching on?
Yup! Or more precisely, the PropVals map inside them - which contains the actual data. Here's the actual implementation I have right now:

```ts
/** Constructs a QuickScore search index from all resources in the store. Does not index commits or resources that are not ready */
function constructIndex(store: Store): SearchIndex {
  const resourceMap: Map<string, Resource> = store.resources;
  const subjectArray = Array.from(resourceMap.values());
  const dataArray = subjectArray.map(resource => {
    // Don't index resources that are loading / errored
    if (!resource.isReady()) return '';
    // Don't index commits
    if (resource.getClasses().includes(urls.classes.commit)) {
      return '';
    }
    // QuickScore can't handle URLs as keys, so I serialize all values of propvals to a single string. https://github.com/fwextensions/quick-score/issues/11
    const propvalsString = JSON.stringify(Array.from(resource.getPropVals().values()));
    const searchResource: FoundResource = {
      subject: resource.getSubject(),
      valuesArray: propvalsString,
    };
    return searchResource;
  });
  // QuickScore requires explicit keys to search through. These should match the keys in FoundResource
  const qsOpts = { keys: ['subject', 'valuesArray'] };
  const qs = new QuickScore(dataArray, qsOpts);
  return qs;
}

/** An instance of QuickScore. See https://fwextensions.github.io/quick-score/ */
interface SearchIndex {
  search: (query: string) => Hit[];
}

interface Hit {
  item: FoundResource;
}

interface FoundResource {
  // The subject of the found resource
  subject: string;
  // JSON serialized array of values combinations
  valuesArray: string;
}
```

> If what you're trying to match on are the routes available on a Resource, I guess I'd break things down into ResourceRoute objects, each with a url, domain, etc. keys. That way, all the items would have the same shape, and if you searched for root, you might get several results, each with a distinct domain. Again, just took a quick look, so I could be off.

Nah, I'm not using the routes. The URLs are mostly just keys, and that's why I've decided to drop them in the above implementation.

**Comment by fwextensions** [comment]
> I just changed that by turning all values into one array, thus ignoring the keys. 

That will ignore the keys, but won't give entirely consistent results.  Matches starting earlier in the string are weighted higher than later ones and `.values()` on a Map returns things in inserted order.  So the same value could show up at different locations in the `valuesArray` string and produce different scores for a given query, even though they'd score the same if they were in separate keys.

Matches against the beginnings of words also score higher, and I just noticed that `,` isn't counted as a word delimiter (which I should fix).  So the `JSON.stringify()` on an array will penalize the beginning of each value, since it inserts commas between each one.  Probably better to do something like `resource.getPropVals().values().sort().join("\n")` to generate the `valuesArray`.

Seems like there are two unmet use cases you've uncovered: 1) optionally ignoring periods in key names and 2) matching against all keys, since the full set of keys is unknown a priori.  

For 1, I can think of a few solutions:

1. Options flag to ignore all periods (though then you can't have a mix of using some as key paths and ignoring others)
2. Use some sort of flag character at the beginning of a key name to ignore dots (though I'm not sure what to use, as almost any char can be used in a quoted key name)
3. Require periods be escaped if they should be ignored, like `"foo\\.bar"` (though may be hard to do without negative lookbehind support)
4. Wrap the key name in an array, like `{ keys: ["title", "name", ["foo.bar"]] }`.  That could also open up supporting arrays as paths, if someone preferred that to single strings, so they could do `{ keys: [["foo", "bar"]] }` instead of `{ keys: ["foo.bar"] }` .  

For 2, your solution of pass an undefined or empty `keys` option when the items are objects probably makes the most sense.

**Comment by joepio** [comment]
>  Probably better to do something like resource.getPropVals().values().sort().join("\n") to generate the valuesArray.

Smart, thanks!

Regarding your options for optionally ignoring periods, my preference would be ordered as 4, 1, 2, 3.

Thanks again for your time.

**Comment by fwextensions** [comment]
I've added support for ignoring dots in the key names and for passing an array of strings for the path in [this branch](https://github.com/fwextensions/quick-score/tree/feature/2021/array-key-paths), which is option 4 above.  I'll look at adding searching on all keys next, without having to specify a list.

**Comment by joepio** [comment]
You're the best, thanks!

**Comment by fwextensions** [comment]
One thing I realized is that the function for sorting search results expects a `defaultKeyName` to sort on when two results have the same score.  This is most useful when a search query is cleared, so that every item has 0 score, and you want the results list sorted alphabetically by each item's, say, `title` key.  

This default key is set to the first item in the `keys` array, which will be empty if an empty array is used as the flag for scoring all keys.  I guess I could say results with identical scores will be returned in an undefined order, but that's not great for the empty query case.

Maybe the "score all keys" behavior should be set via a `scoreAllKeys` flag passed to the `QuickScore()` constructor.  Or the default key could instead be specified by a separate flag.  So it would default to the first key in `keys`, but you could also specify it like `{ keys: [], defaultKey: "title" }`.  Not sure which is better, or if there's a simpler option.

**Comment by fwextensions** [comment]
Support for array paths and scoring all keys on an object is now in 0.1.1 on npm.  A `sortKey` param lets you specify a key to use to sort identically scored items even when the `keys` array is empty.
