### ISSUE TITLE
Implement highlight for matches

### ISSUE THREAD

**Issue by devgar** [fwextensions/quick-score#3]
`QuickScore` for list sorting could return a representation of the strings with highlighted matches in the extended values.

```js
[
    {
        "item": "GitHub",
        "score": 0.9166666666666666,
        "matches": [[0, 1], [3, 4]],
        "highlighted": "<b>G</b>it<b>H</b>ub"
    },
    {
        "item": "hello, Garth",
        "score": 0.6263888888888888,
        "matches": [[7, 8], [11, 12]],
        "highlighted": "hello, <b>G</b>art<b>h</b>"
    },
    ...
```
Could use a function like this:
```js
function highlight(msg, matches)
{
  let m = msg
  for ([start, end] of matches.reverse())
  {
    m = m.slice(0, start) + m.slice(start, end).bold() + m.slice(end, m.length)
  }
  return m
}
```

**Comment by devgar** [comment]
Lol, I haven't ended the Readme? There's a highlighting section. 

So, I still purpose including a highlighting method.

**Comment by fwextensions** [comment]
RTFM!  ;)  

I could see adding a utility function that, given an array of `matches`, wraps the match in some user-supplied string, or calls a user-supplied function that can return the wrapped match.  But I wouldn't want to assume the developer would always want HTML strings as opposed to something like React.

Perhaps it could be an option, but I also think you wouldn't necessarily want to pre-wrap every matching result, since you likely won't ever render all of them if it's a long list.

**Comment by devgar** [comment]
Yeah, you changed my mind. I close this. So I also discovered it's not so difficult to write a highlighting function. XP
